### ISSUE TITLE
Downgrading to 3.60 keeps failing

### ISSUE THREAD

**Issue by AqilaAdnandana** [TheOfficialFloW/modoru#19]
27 March at night, i downgraded the ps vita to 3.60 and my vita failed to complete update. when i try again the update, it keeps failing then my vita become black screen.

Note: My vita fat used Modoru 1.0 then, i see a error

**Comment by afandiyusuf** [comment]
Same problem, here, and now my ps vita can not turn on again (only button ps turn on for a while then blipping and turn off again), screen completely black.

When I go to safe mode, all menu disabled except the last menu "update this system"
I think the problem is, I accidentally put normal firmware rather than complete firmware.


How to resolve this?
Help.

**Comment by TheOfficialFloW** [comment]
Your vita soft bricked. Please go to r/vitahacks or google that issue to resolve it.
