### ISSUE TITLE
Downgrade Update Error ??

### ISSUE THREAD

**Issue by last0ne75** [TheOfficialFloW/modoru#24]
Hi guys, today I tried to downgrade my PsVita 1000 3.73 to 3.60 by using Modoru V2.2 . I watched a video and I did everything right but when I star to downgrade after the system update, the system reboot and get stuck in the black screen with logo PS. I can't open the safe mod even If I hold the power button for 30 seconds. I can only power off and power on the PsVita. What should I do please help me.

**Comment by gb4ll4** [comment]
Hi, guys.

I got a similar error 2 weeks ago when I wanted to downgrade to 3.60. I used moduro 2.2, everyting went fine until restart. 
On restart I also stuck the same PS logo screen. However I manage to boot into recovery mode, but I also sutck with a "Please wait" message when I want to update back to 3.73 (unbrick) to start over with moduro 2.1. I tried to update with Windows, Linux QCMA, and PS3. 

I got this output from qcma -verbose:
"
Starting cma threads
Starting usb_thread: 0x00007fe5ae527700
Using protocol mode: "automatic"
Starting wireless_thread: 0x00007fe5add26700
Waiting for wireless connection
VitaMTP: waiting for connection
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 03274195194122048
Using protocol mode: "automatic"
Sending Qcma protocol version: 1900010
Identifying as "gballa-Business-PC-5200-P8Q77M"
Starting event loop
Starting event_thread: 0x00007fe5ad525700
Icon changed - connected
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 1
Found request for update list. Sending embedded xml file
Detected country code from URL: "uk"
Setting XML version to 03.730.000
Sending 572 bytes of data for HTTP request http://fuk01.psp2.update.playstation.net/.../psp2...
Ended event, code: 0xc10b, id: 1
"

After this point this process is stucked, and I have to power off the Vita to abort.

My Vita is still briced since, I would like try to solve this on the software side before I buy a new mainboard.
Thank you for your help in advance.

**Comment by RegeditJPN** [comment]
I think it´s a brick (obviously), in the worst case. But it can be a "semibrick", that it´s like a brick but with a solution can be fixed by plugging your Vita to a PS3.
Anyways, if it´s a brick I think it can´t be fixed.
